
import { LevelTopic } from './types';

export const LEVEL_TOPICS: LevelTopic[] = [
  {
    level: 'Beginner',
    topics: [
      'Chessboard, Pieces & Rook',
      'Bishop, Queen, Pawn & Notation',
      'King, Knight & Piece Values',
      'Capture Basics & Hanging Pieces',
      'Defending – ABCD Method',
      'Checks, Defense & Checkmate Intro',
      'Opening: Control the Center',
      'Opening: Develop Minor Pieces',
      'Opening: King Safety & Castling',
      'Opening: Don’t move the same piece again',
      'Opening: Don’t bring Queen early',
      'Capturing – Mixed Practice',
      'Beginner Test 1',
      'Checks & Defending – Practice',
      'Mate in 1 & Basic Strategies',
      'Castling Deep Dive',
      'En Passant & Promotion',
      'Assisted Mates in 1',
      'Correct Captures',
      'Good Exchanges',
      'Beginner Test 2',
      'Mate – Mixed Exercises',
      'Draws – Stalemate & Rules',
      'Draws – Other Rules',
      'Special Moves & Draws – Mixed'
    ]
  },
  {
    level: 'Foundation 1',
    topics: [
      'Revision of Beginner Topics',
      'Queen & Two Rooks Checkmate – Revision',
      'Tactics: The Pin',
      'Tactics: The Skewer',
      'Tactics: Double Attack',
      'Tactics: Knight Fork',
      'Foundation Opening Principles',
      'Opening: Control the Center (Simple)',
      'Opening: Develop Knight before Bishop',
      'Opening: Early King Safety',
      'Opening: Common Beginner Mistakes',
      'Opening: Simple Sample Openings',
      'Discovered Check & Double Check',
      'Foundation 1 Test [1]',
      'Mate in 1 – Mixed Practice',
      'Opening Traps & Patterns',
      'Defending Against Checkmate',
      'Punishing Bad Opening Moves',
      'Back-Rank Mate Patterns',
      'Simple Checkmate in 2 Moves',
      'Destroying & Distracting the Defender',
      'Foundation 1 Test [2]',
      'Checkmate with One Rook',
      'Queen vs Bishop & Queen vs Knight',
      'Mixed Tactics Challenge',
      'Checkmate Threats & Recognition'
    ]
  },
  {
    level: 'Foundation 2',
    topics: [
      'Revision of Foundation-1',
      'Trapping the Pieces',
      'Tactics: Overloading',
      'Tactics: X-Ray Attack',
      'Tactics: Decoy / Deflection',
      'Opening Traps Mastery',
      'Advanced Opening: Development with Purpose',
      'Advanced Opening: Open Files & Diagonals',
      'Advanced Opening: Breaking Rules & Punishing Greed',
      'Opening to Middlegame Connection',
      'Intermediate Moves (Zwischenzug)',
      'Foundation 2 Test [1]',
      'Endgame: Rule of the Square',
      'Endgame: Key Squares & Opposition',
      'King & Pawn vs King (4 Scenarios)',
      'Pawn Breakthroughs',
      'Tactics: The Windmill',
      'Forced Moves & Calculation',
      'Smothered Mate Patterns',
      'Foundation 2 Test [2]',
      'Mate Patterns: Legal’s & Epaulette',
      'Mate Patterns: Anastasia & Arabian',
      'Mate Patterns: Boden’s & Dovetail',
      'Mate Patterns: Battery & Hook'
    ]
  },
  {
    level: 'Foundation 3',
    topics: [
      'Revision of Foundation 2',
      'Checkmate in 3 (Easy)',
      'Introduction to World Champions',
      'Attacking on h7 Ideas',
      'Mixed Tactics (3 Moves)',
      'Endgame: Queen vs 7th Rank Pawn',
      'Student Game Review [Session 1]',
      'Foundation 3 Test 1',
      'Checkmate in 3 (Difficult)',
      'Meet India\'s 1st WC & Short Game',
      'Attacking on g7 Ideas',
      'Mixed Tactics (3 Moves) - Advanced',
      'Stalemate Tactics',
      'Endgame: King & Pawn vs King (Advanced)',
      'Student Game Review [Session 2]',
      'Foundation 3 Test 2',
      'Meet the Magician & Short Games',
      'Attacking on f7 Ideas',
      'Mixed Tactics (3 Moves) - Master',
      'Drawing Tactics',
      'Endgame: King & Pawn vs King (Above the Basic)',
      'Student Game Review [Session 3]',
      'Checkmate in 4 (Easy)',
      'Foundation 3 Test 3'
    ]
  },
  {
    level: 'Intermediate',
    topics: [
      'How to calculate (intro)',
      'Centralisation of the King',
      'Finding Candidate Moves (Checks, Captures, Threats)',
      'Principle of Two Weaknesses',
      'World Champion Study: Vishy Anand',
      'Strategic Rule: Do Not Hurry',
      'Structure: e4-e5 Italian structures',
      'Intermediate Monthly Test [1]',
      'Blunder Check Techniques',
      'Endgame: Passed Pawns',
      'Logic: Process of Elimination',
      'Schematic Thinking',
      'World Champion Study: Anatoly Karpov',
      'Transformation of Material Advantage',
      'Structure: e4-e5 Scotch structure',
      'Intermediate Monthly Test [2]',
      'Forcing Moves Calculation',
      'Rook Activity Principles',
      'The Initiative',
      'Pawn Breaks',
      'World Champion Study: Garry Kasparov',
      'Good Knight vs Bad Bishop Part 1',
      'Exchange Sacrifice (Thematic)',
      'Intermediate Monthly Test [3]',
      'Developing Intuition',
      'Good Bishop vs Bad Knight Part 1',
      'Basic Endgame Tactics',
      'Double Bishop Power Part 1',
      'World Champion Study: Bobby Fischer',
      'Multiple Minor Piece Endgames',
      'Structure: e4-c6 Caro-Kann structures',
      'Intermediate Monthly Test [4]',
      'King Safety Mastery',
      'Practical Rook Endgames Part 1',
      'Space Advantage Part 1',
      'Practical Rook Endgames Part 2',
      'World Champion Study: Alexander Alekhine',
      'World Champion Study: Jose Raul Capablanca',
      'Structure: e4-c5 Sicilian Boleslavsky',
      'Intermediate Monthly Test [5]',
      'Piece Activity Principles',
      'Practical Queen Endgames Part 1',
      'Material Advantage & Pawn Structure (Intro)',
      'Practical Queen Endgames Part 2',
      'Key Squares and Outposts',
      'Legend Study: Akiba Rubinstein',
      'Advanced Tactics Challenge',
      'Intermediate Monthly Test [6]',
      'Isolated and Doubled Pawns',
      'Cut off & Back Rank Defense',
      'Backward & Hanging Pawns',
      'Endgame: Lucena and Philidor Positions',
      'World Champion Study: Mikhail Botvinnik',
      'Strategy Study: Ulf Andersson',
      'Prophylaxis: Anticipating Opponent’s Ideas',
      'Intermediate Monthly Test [7]',
      'Passer, Majority vs Minority',
      'Short Side vs Long Side Defense',
      'Isolated Queen Pawn (IQP) Structures',
      'Endgame: 3 vs 2 and 4 vs 3 Pawns',
      'Legend Study: Viktor Korchnoi',
      'World Champion Study: Magnus Carlsen',
      'Transition from Middlegame to Endgame',
      'Intermediate Monthly Test [8]',
      'Pawn Chains Part 1',
      'Pawn Endgames Deep Dive',
      'Opening Family: The Sicilian',
      'Bishop + Knight Checkmate Technique',
      'Slav/Caro-Kann/QGD Pawn Families',
      'Strategic Mastery: Anatoly Karpov II',
      'Handling Material Imbalances (R+P vs 2 Minors)',
      'Intermediate Monthly Test [9]',
      'Opening Family: KID/Benoni',
      'Endgame: Same Color Bishop Endings',
      'Power of the Two Bishops',
      'Endgame: Opposite Color Bishop Endings',
      'Opposite-Coloured Bishops in Middlegame',
      'World Champion Study: Vasily Smyslov',
      'Weaknesses: Creating and Exploiting Targets',
      'Intermediate Monthly Test [10]',
      'Good Knight vs Bad Bishop Deep Dive',
      'Fortress Draw Concepts',
      'Bad Piece Manoeuvring Part 1',
      'Winning Equal Endgames',
      'Attacking Uncastled King Part 1',
      'Elite Study: Pentala Harikrishna',
      'Fortress Concepts in Practice',
      'Intermediate Monthly Test [11]',
      'Attacking the Castled King Part 1',
      'The Queenless Middlegame',
      'Sacrifice for Initiative',
      'Defending Worse Positions',
      'Generating Counterplay',
      'Legend Study: Yuri Averbakh',
      'Defending Worse Positions: Mindset & Technique',
      'Intermediate Monthly Test [12]'
    ]
  },
  {
    level: 'Advance',
    topics: [
      'Queen vs Rook and Minor Piece',
      'Queen vs Two Rooks',
      'Queen vs Two Minor Pieces',
      'Piece for Three Pawns (Deep Positional Cases)',
      'When You Can’t Think of a Plan',
      'Inferior Positions (Playing Objectively Worse)',
      'Strategic Decision Making',
      'Long-Term Advantages',
      'The Curse of Passivity (High-Level Cases)',
      'The Dominant Knight',
      'Excluding Defensive Pieces',
      'Surprise Moves',
      'Positional Pawn Sacrifices (Advanced, Non-forcing)',
      'Positional Exchange Sacrifices',
      'Other Positional Sacrifices',
      'Marginal Sacrifices',
      'Disaster on g7',
      'Bxh6 Sacrifice',
      'Nd5 Sacrifice in the Sicilian',
      'Nxe6 Sacrifice in the Sicilian',
      'Nf5 Sacrifice in the Sicilian',
      'Rxc3 in the Sicilian',
      'Attack against the Fianchetto',
      'Deadly Long Diagonal',
      'Breakthrough to the King',
      'All-Out Attack Concepts',
      'Risks of Attacking (When NOT to Attack)',
      'Exchanging Attacking Pieces',
      'Defensive Sacrifice',
      'Coolness under Fire',
      'Running with the King',
      'Don’t Panic! (Practical Defence Mindset)',
      'Hanging Pawns (Deep Middlegame Plans)',
      'Weak Colour Complex',
      'Sacrificial Demolition of Pawn Chains',
      'Overvaluing Material (Advanced Cases)',
      'Evaluation Errors under Pressure',
      'Alertness & Practical Decision Errors',
      'Active vs Passive Rook',
      'Rook + Pawn vs Rook (Vancura Position)',
      'Converting an Extra Pawn in Rook Endgames',
      'Defending Worse Rook Endgames',
      'Rook Endgames – One Wing (3v2 / 4v3)',
      'Rook Endgames – Both Wings',
      'Bishop vs Knight Endgames (Both Wings)',
      'Same-Coloured Bishop Endgames (Extra Pawn)',
      'Knight vs Pawns (Outside Passed Pawn)',
      'Creating a Second Weakness in Endgames',
      'Zugzwang in Practical Endgames',
      'Outside Passed Pawn Strategy',
      'Fortress Recognition (Complex Positions)',
      'Holding Draws a Pawn Down',
      'Queen Endgames – Activity vs Safety',
      'Queen Endgames with Passed Pawns',
      'Perpetual Check vs Winning Attempts',
      'Transition from Middlegame to Endgame',
      'Simplifying from Advantage',
      'Avoiding Simplification when Worse',
      'Playing for a Win vs Playing for a Draw',
      'Practical Endgames & Time-Trouble Decisions'
    ]
  },
  {
    level: 'Advance 2',
    topics: [
      'Elite Performance: Global Ranking Strategies',
      'High-Stakes Psychology & Mindset',
      'Customer-Based Custom Learning Pathways',
      'Advanced Tournament Preparation & Scouting',
      'Mastering the World-Class Advantage',
      'Academy Capstone: Path to World Number One'
    ]
  }
];

export const COURSES = [
  'Chess Masterclass',
  'Full Stack Web', 
  'Python Data Science', 
  'Mobile App Dev', 
  'Cyber Security',
  'AI & Machine Learning'
];
